name: test

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15, ubuntu-22.04, ubuntu-24.04, windows-latest]
        go: ['1.21', '1.22', '1.23', '1.24', '1.25']

    runs-on: ${{matrix.os}}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}

      - name: apt
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install libsecret-1-dev pkg-config

      - name: build
        run: go build

  test-dragonfly:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: dragonfly-vm
        uses: vmactions/dragonflybsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y go libsecret pkgconf
          run: |
            uname -a
            go version
            git config --add --global safe.directory "$PWD"
            go build

  test-freebsd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: freebsd-vm
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: pkg install -y go libsecret pkgconf
          run: |
            uname -a
            go version
            go build

  test-netbsd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: netbsd-vm
        uses: vmactions/netbsd-vm@v1
        with:
          prepare: pkg_add go libsecret pkg-config pkg_alternatives
          run: |
            uname -a
            go version
            go build

  test-openbsd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: openbsd-vm
        uses: vmactions/openbsd-vm@v1
        with:
          prepare: |
            for i in $(jot 10); do
              echo attempt $i:
              pkg_add -vv go && break
            done
          run: |
            uname -a
            go version
            go build
